In [42]:
import pandas as pd
import random
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

In [3]:
dataset = pd.read_csv('/home/nunesfi/Desktop/IA/files/Bases de dados-20230823T013645Z-001/Bases de dados/census.csv')

In [4]:
dataset

age          workclass  final-weight    education  education-num  \
0       39          State-gov         77516    Bachelors             13   
1       50   Self-emp-not-inc         83311    Bachelors             13   
2       38            Private        215646      HS-grad              9   
3       53            Private        234721         11th              7   
4       28            Private        338409    Bachelors             13   
...    ...                ...           ...          ...            ...   
32556   27            Private        257302   Assoc-acdm             12   
32557   40            Private        154374      HS-grad              9   
32558   58            Private        151910      HS-grad              9   
32559   22            Private        201490      HS-grad              9   
32560   52       Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
0         Male          2174             0             40   United-States   
1         Male             0             0             13   United-States   
2         Male             0             0             40   United-States   
3         Male             0             0             40   United-States   
4       Female             0             0             40            Cuba   
...        ...           ...           ...            ...             ...   
32556   Female             0             0             38   United-States   
32557     Male             0             0             40   United-States   
32558   Female             0             0             40   United-States   
32559     Male             0             0             20   United-States   
32560   Female         15024             0             40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [9]:
# amostragem aleatória simples
df_amostra_aleatoria_simples = dataset.sample(n=100, random_state=1)

In [10]:
df_amostra_aleatoria_simples.shape

(100, 15)

In [11]:
def amostragem_aleatoria_simples(dataset, amostras):
    return dataset.sample(n = amostras)

In [12]:
df_amostra_aleatoria_simples = amostragem_aleatoria_simples(dataset,100)

## Amostragem Sistemática

In [13]:
dataset.shape

(32561, 15)

In [15]:
len(dataset) // 100

325

In [21]:
#Escolher um numero randominco de  0 a 325, o seed faz com que comece sempre do numero 1
random.seed(1)
random.randint(0,325)

68

In [23]:
np.arange(68, len(dataset), step=325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [24]:
def amostragem_sistematica(dataset, amostras):
    intervalo = len(dataset) // amostras
    random.seed(1)
    inicio = random.randint(0, intervalo)
    indices = np.arange(inicio, len(dataset), step = intervalo)
    amostra_sistematica = dataset.iloc[indices]
    return amostra_sistematica

In [26]:
df_amostra_sistematica = amostragem_sistematica(dataset, 100)
df_amostra_sistematica.shape

(100, 15)

## Amostragem por Grupos

In [27]:
len(dataset)

32561

In [28]:
grupos = []
id_grupo = 0
contagem = 0

for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > 3256:
        contagem = 0
        id_grupo +=1

In [31]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [32]:
np.shape(grupos), dataset.shape

((32561,), (32561, 15))

In [33]:
dataset['grupos'] = grupos

In [34]:
dataset

age          workclass  final-weight    education  education-num  \
0       39          State-gov         77516    Bachelors             13   
1       50   Self-emp-not-inc         83311    Bachelors             13   
2       38            Private        215646      HS-grad              9   
3       53            Private        234721         11th              7   
4       28            Private        338409    Bachelors             13   
...    ...                ...           ...          ...            ...   
32556   27            Private        257302   Assoc-acdm             12   
32557   40            Private        154374      HS-grad              9   
32558   58            Private        151910      HS-grad              9   
32559   22            Private        201490      HS-grad              9   
32560   52       Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
0         Male          2174             0             40   United-States   
1         Male             0             0             13   United-States   
2         Male             0             0             40   United-States   
3         Male             0             0             40   United-States   
4       Female             0             0             40            Cuba   
...        ...           ...           ...            ...             ...   
32556   Female             0             0             38   United-States   
32557     Male             0             0             40   United-States   
32558   Female             0             0             40   United-States   
32559     Male             0             0             20   United-States   
32560   Female         15024             0             40   United-States   

       income  grupos  
0       <=50K       0  
1       <=50K       0  
2       <=50K       0  
3       <=50K       0  
4       <=50K       0  
...       ...     ...  
32556   <=50K       9  
32557    >50K       9  
32558   <=50K       9  
32559   <=50K       9  
32560    >50K       9  

[32561 rows x 16 columns]

In [36]:
random.randint(0,9)

1

In [37]:
df_agrupamento = dataset[dataset['grupos'] == 7]

In [38]:
df_agrupamento

age          workclass  final-weight      education  education-num  \
22799   25   Self-emp-not-inc         21472   Some-college             10   
22800   32            Private         90969      Assoc-voc             11   
22801   26            Private        149734        HS-grad              9   
22802   42            Private         52849   Some-college             10   
22803   39   Self-emp-not-inc        106347   Some-college             10   
...    ...                ...           ...            ...            ...   
26051   19                  ?        141418   Some-college             10   
26052   19            Private        306225        HS-grad              9   
26053   35            Private        330664        HS-grad              9   
26054   43            Private        191765        HS-grad              9   
26055   45            Private        289353        HS-grad              9   

            marital-status          occupation    relationship    race  \
22799        Never-married       Other-service   Not-in-family   White   
22800   Married-civ-spouse    Transport-moving         Husband   White   
22801            Separated        Craft-repair       Unmarried   Black   
22802   Married-civ-spouse   Machine-op-inspct         Husband   White   
22803             Divorced               Sales       Unmarried   White   
...                    ...                 ...             ...     ...   
26051        Never-married                   ?       Own-child   White   
26052        Never-married   Handlers-cleaners       Own-child   White   
26053             Divorced    Transport-moving   Not-in-family   White   
26054             Divorced        Tech-support       Unmarried   Black   
26055   Married-civ-spouse    Transport-moving         Husband   Black   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
22799   Female             0             0             22   United-States   
22800     Male             0             0             45   United-States   
22801   Female             0          1594             40   United-States   
22802     Male             0             0             40   United-States   
22803     Male             0             0             47   United-States   
...        ...           ...           ...            ...             ...   
26051     Male             0             0             15   United-States   
26052     Male             0             0             25   United-States   
26053     Male             0             0             40   United-States   
26054   Female             0             0             35   United-States   
26055     Male             0             0             24   United-States   

       income  grupos  
22799   <=50K       7  
22800    >50K       7  
22801   <=50K       7  
22802   <=50K       7  
22803   <=50K       7  
...       ...     ...  
26051   <=50K       7  
26052   <=50K       7  
26053   <=50K       7  
26054   <=50K       7  
26055   <=50K       7  

[3257 rows x 16 columns]

In [40]:
def amostragem_agrupamento(dataset, numero_grupos):
    intervalo = len(dataset) / numero_grupos

    grupos = []
    id_grupo = 0
    contagem = 0

    for _ in dataset.iterrows():
        grupos.append(id_grupo)
        contagem += 1
        if contagem > intervalo:
            contagem = 0
            id_grupo +=1
    
    dataset['grupos'] == grupos
    grupo_selecionado = random.randint(0, numero_grupos)
    return dataset[dataset['grupos'] == grupo_selecionado]

In [41]:
df_amostra_agrupamento = amostragem_agrupamento(dataset, 100)
df_agrupamento.shape, df_amostra_agrupamento['grupos'].value_counts()

((3257, 16), Series([], Name: grupos, dtype: int64))

## Amostra estratificada

In [43]:
dataset['income'].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [44]:
split = StratifiedShuffleSplit(test_size=0.1)
for x, y in split.split(dataset, dataset['income']):
    df_x = dataset.iloc[x]
    df_y = dataset.iloc[y]

## Amostra de Reservatório

In [45]:
stream = []

for i in range(len(dataset)):
    stream.append(i)

In [ ]:
def amostragem_reservatorio(dataset, amostras):
    stream = []
    for i in range(len(dataset)):
        stream.append(i)

    i = 0
    tamanho = len(dataset)

    reservatorio = [0] * amostras
    for i in range(amostras):
        reservatorio[i] = stream[i]

    while i < tamanho:
        j = random.randrange(i + 1)
        if j < amostras:
            reservatorio[j] = stream[i]
        i += 1

    return dataset.iloc[reservatorio]