In [2]:
pip install plotly --upgrade

Note: you may need to restart the kernel to use updated packages.


In [57]:
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from yellowbrick.regressor import ResidualsPlot
import plotly.graph_objects as go

## Base Plano de saude

In [4]:
base_plano_saude2 = pd.read_csv('/home/nunesfi/Desktop/IA/files/Bases de dados-20230823T013645Z-001/Bases de dados/plano_saude2.csv')
base_plano_saude2

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [5]:
x_plano_saude2 = base_plano_saude2.iloc[:,0:1].values
x_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [6]:
y_plano_saude2 = base_plano_saude2.iloc[:,1].values
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [7]:
poly = PolynomialFeatures(degree=2)
x_plano_saude2_poly = poly.fit_transform(x_plano_saude2)

In [8]:
x_plano_saude2_poly[1]

array([  1.,  23., 529.])

In [9]:
regressor_saude_polinomial = LinearRegression()
regressor_saude_polinomial.fit(x_plano_saude2_poly,y_plano_saude2)

LinearRegression()

In [10]:
# b0
regressor_saude_polinomial.intercept_

7133.836363636174

In [11]:
#b1
regressor_saude_polinomial.coef_

array([   0.        , -469.89393939,    7.82121212])

In [12]:
novo = [[40]]
novo = poly.transform(novo)
regressor_saude_polinomial.predict(novo)

array([852.01818182])

In [13]:
previsoes = regressor_saude_polinomial.predict(x_plano_saude2_poly)
previsoes

array([1209.81818182,  463.6969697 ,  108.63636364,  144.63636364,
        571.6969697 , 1389.81818182, 2599.        , 4199.24242424,
       6190.54545455, 8572.90909091])

In [14]:
grafico = px.scatter(x = x_plano_saude2[:,0], y = y_plano_saude2)
grafico.add_scatter(x= x_plano_saude2[:,0], y = previsoes, name= 'Regressão')
grafico.show()

## Regressão - Arvores de Decisão

In [15]:
x_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [16]:
regressor_arvore_saude = DecisionTreeRegressor()
regressor_arvore_saude.fit(x_plano_saude2, y_plano_saude2)

DecisionTreeRegressor()

In [17]:
previsoes = regressor_arvore_saude.predict(x_plano_saude2)
previsoes

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [18]:
regressor_arvore_saude.score(x_plano_saude2,y_plano_saude2)

1.0

In [19]:
grafico = px.scatter(x = x_plano_saude2[:,0], y = y_plano_saude2)
grafico.add_scatter(x= x_plano_saude2[:,0], y = previsoes, name= 'Regressão')
grafico.show()

In [20]:
x_teste_arvore = np.arange(min(x_plano_saude2), max(x_plano_saude2), step=0.1 )
x_teste_arvore

/tmp/ipykernel_232229/616746261.py:1: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33

In [21]:
x_teste_arvore = x_teste_arvore.reshape(-1,1)

In [22]:
grafico = px.scatter(x = x_plano_saude2.ravel(), y = y_plano_saude2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y = regressor_arvore_saude.predict(x_teste_arvore), name= 'Regressão')
grafico.show()

In [23]:
regressor_arvore_saude.predict([[40.6]])

array([1530.])

## Base preços das casas

In [24]:
base_casas = pd.read_csv('/home/nunesfi/Desktop/IA/files/Bases de dados-20230823T013645Z-001/Bases de dados/house_prices.csv')

In [25]:
x_casas = base_casas.iloc[:,5:6].values
y_casas = base_casas.iloc[:,2].values

In [26]:
x_casas_treinamento, x_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(x_casas, y_casas, test_size=0.3, random_state=0)

In [27]:
regressor_arvore_casas = DecisionTreeRegressor()
regressor_arvore_casas.fit(x_casas_treinamento, y_casas_treinamento)

DecisionTreeRegressor()

In [28]:
regressor_arvore_casas.score(x_casas_treinamento, y_casas_treinamento)

0.6333418801272528

In [29]:
regressor_arvore_casas.score(x_casas_teste, y_casas_teste)

0.4938582480846785

In [30]:
previsoes = regressor_arvore_casas.predict(x_casas_teste)
previsoes

array([ 371652.48148148, 1119000.        ,  367642.        , ...,
        509418.78      ,  430163.03571429,  368505.30588235])

## Random Forest - Regressão Linear

In [31]:
regressor_random_forest_saude = RandomForestRegressor(n_estimators=10)
regressor_random_forest_saude.fit(x_plano_saude2, y_plano_saude2)

RandomForestRegressor(n_estimators=10)

In [32]:
regressor_random_forest_saude.score(x_plano_saude2, y_plano_saude2)

0.9315559072661032

In [33]:
grafico = px.scatter(x = x_plano_saude2.ravel(), y = y_plano_saude2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y = regressor_random_forest_saude.predict(x_teste_arvore), name= 'Regressão')
grafico.show()

In [34]:
regressor_random_forest_saude.predict([[40]])

array([1207.])

## Base preço das casas

In [35]:
x_casas_treinamento.shape

(15129, 1)

In [36]:
y_casas_treinamento

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [37]:
x_casas_teste

array([[1430],
       [4670],
       [1440],
       ...,
       [2150],
       [1480],
       [1320]])

In [38]:
regressor_random_forest_casas = RandomForestRegressor(n_estimators=100)
regressor_random_forest_casas.fit(x_casas_treinamento,y_casas_treinamento)

RandomForestRegressor()

In [39]:
regressor_random_forest_casas.score(x_casas_treinamento,y_casas_treinamento)

0.6206914818650762

In [40]:
regressor_random_forest_casas.score(x_casas_teste,y_casas_teste)

0.5060293267747124

In [41]:
previsoes = regressor_random_forest_casas.predict(x_casas_teste)
previsoes

array([ 370451.40580811, 1212586.02222222,  368236.97949141, ...,
        509815.85619983,  426882.01603043,  368510.59032094])

In [42]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [43]:
mean_absolute_error(y_casas_teste,previsoes)

168734.1297917592

## Regressão Linear SVM

In [44]:
#kernel linear
regressor_svr_saude_linear = SVR(kernel='linear')
regressor_svr_saude_linear.fit(x_plano_saude2, y_plano_saude2)

SVR(kernel='linear')

In [45]:
grafico = px.scatter(x = x_plano_saude2.ravel(), y = y_plano_saude2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y = regressor_svr_saude_linear.predict(x_teste_arvore), name= 'Regressão')
grafico.show()

In [46]:
#kernel polinomial
regressor_svr_saude_poly = SVR(kernel='poly', degree=4)
regressor_svr_saude_poly.fit(x_plano_saude2,y_plano_saude2)

SVR(degree=4, kernel='poly')

In [47]:
grafico = px.scatter(x = x_plano_saude2.ravel(), y = y_plano_saude2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y = regressor_svr_saude_poly.predict(x_teste_arvore), name= 'Regressão')
grafico.show()

In [48]:
scaler_x = StandardScaler()
x_plano_saude2_scaled = scaler_x.fit_transform(x_plano_saude2)
scaler_y = StandardScaler()
y_plano_saude2_scaled = scaler_y.fit_transform(y_plano_saude2.reshape(-1,1))

In [49]:
#kernel rbf
regressor_svr_saude_rbf = SVR(kernel='rbf')
regressor_svr_saude_rbf.fit(x_plano_saude2_scaled,y_plano_saude2_scaled)

/home/nunesfi/Desktop/IA/env_ia/lib/python3.10/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



SVR()

In [50]:
grafico = px.scatter(x = x_plano_saude2_scaled.ravel(), y = y_plano_saude2_scaled.ravel())
grafico.add_scatter(x= x_plano_saude2_scaled.ravel(), y = regressor_svr_saude_rbf.predict(x_plano_saude2_scaled), name= 'Regressão')
grafico.show()

In [51]:
regressor_svr_saude_rbf.predict([[40]])

array([0.01359678])

In [52]:
novo = [[40]]

In [53]:
novo = scaler_x.transform(novo)
novo

array([[-0.03481553]])

In [54]:
x_casas_treinamento.shape

(15129, 1)

In [55]:
x_casas_teste.shape

(6484, 1)

## Rede neural

In [56]:
x_plano_saude2_scaled

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [60]:
regressor_rna_saude = MLPRegressor(max_iter=1000)
regressor_rna_saude.fit(x_plano_saude2_scaled,y_plano_saude2_scaled.ravel())

MLPRegressor(max_iter=1000)

In [61]:
regressor_rna_saude.score(x_plano_saude2_scaled,y_plano_saude2_scaled)

0.9663004235063617

In [62]:
grafico = px.scatter(x = x_plano_saude2_scaled.ravel(), y = y_plano_saude2_scaled.ravel())
grafico.add_scatter(x= x_plano_saude2_scaled.ravel(), y = regressor_rna_saude.predict(x_plano_saude2_scaled), name= 'Regressão')
grafico.show()

In [63]:
novo = [[40]]
novo = scaler_x.transform(novo)
regressor_rna_saude.predict(novo)

array([-0.4798333])